FROM python:3

RUN mkdir /usr/src/app

WORKDIR /usr/src/app

COPY ./Requirements.txt .

RUN pip install -r Requirements.txt

# COPY . /usr/src/app

RUN mkdir /usr/src/app/uploads

RUN apt install ffmpeg

EXPOSE 5000

CMD ["python", "app.py"]