version: "3"
services:
  app:
    container_name: main_service
    restart: always
    build: 
      context: .
    ports:
      - 3000:5000
    volumes: 
      - .:/usr/src/app
    networks:
      - service_network

networks:
  service_network:
