version: "3"
services:
  gateway:
    container_name: gateway_service
    restart: always
    build: 
      context: ./gateway
      dockerfile: Dockerfile.dev
    ports:
      - 3000:5000
    volumes: 
      - ./gateway:/usr/src/app
    depends_on:
      - soundutils
    networks:
      - service_network
    environment:
      SOUNDUTILS_HOST: soundutils
      SOUNDUTILS_PORT: 5000

  soundutils:
    container_name: sound_utils_service
    restart: always
    build: 
      context: ./sound-utils
      dockerfile: Dockerfile.dev
    ports:
      - "3001:5000"
    volumes: 
      - ./sound-utils:/usr/src/app
    networks:
      - service_network

networks:
  service_network:
